---
- hosts: localhost
  connection: local
  gather_facts: true    # gather OS info that is made available for tasks/roles
  become: yes           # majority of CIS tasks require root
  vars:
    # CIS Controls whitepaper:  http://bit.ly/2mGAmUc
    # AWS CIS Whitepaper:       http://bit.ly/2m2Ovrh
    rhel7cis_selinux_pol: targeted
    rhel7cis_selinux_disable: true
    rhel7cis_is_mail_server: false
    hel7cis_avahi_server: false
    rhel7cis_cups_server: false
    rhel7cis_dhcp_server: false
    rhel7cis_ldap_server: false
    rhel7cis_telnet_server: false
    rhel7cis_nfs_server: false
    rhel7cis_rpc_server: false
    rhel7cis_ntalk_server: false
    rhel7cis_rsyncd_server: false
    rhel7cis_tftp_server: false

    # Chrony
    rhel7cis_time_synchronization: chrony
    rhel7cis_time_synchronization_servers:
      - '169.254.169.123'

    # 3.4.2, 3.4.3 and 3.6.2 effectively blocks access to all ports to the machine
    ## This can break automation; ignoring it as there are stronger mechanisms than that
    rhel7cis_rule_1_1_2: false
    rhel7cis_rule_1_1_3: false
    rhel7cis_rule_1_1_4: false
    rhel7cis_rule_1_1_5: false
    rhel7cis_rule_3_4_2: false
    rhel7cis_rule_3_4_3: false
    rhel7cis_rule_3_6_2: false

    # Cloudwatch Logs will be used instead of Rsyslog/Syslog-ng
    ## Same would be true if any other software that doesn't support Rsyslog/Syslog-ng mechanisms
    rhel7cis_rule_4_2_1_4: false
    rhel7cis_rule_4_2_2_4: false
    rhel7cis_rule_4_2_2_5: false

    # Autofs is no longer installed and we need to ignore it or else will fail
    rhel7cis_rule_1_1_19: false

    # Password reuse limit task fails due to AttributionError in Ansible code; skipping
    rhel7cis_rule_5_3_3: false

    # Cloudwatch Logs Role configuration
    logs:
      - file: /var/log/messages
        group_name: "system_logs"
  roles:
    - common
    - RHEL7-CIS
